# Generated by Django 4.0.4 on 2022-04-29 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Компания')),
                ('location', models.CharField(max_length=50, verbose_name='Город')),
                ('logo', models.ImageField(upload_to='job_site_app/static/logo/', verbose_name='Лого')),
                ('description', models.TextField(verbose_name='Информация о компании')),
                ('employee_count', models.IntegerField(verbose_name='Количество сотрудников')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Специализация')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('picture', models.ImageField(upload_to='job_site_app/static/picture/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Вакансия')),
                ('skills', models.TextField(verbose_name='Навыки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('salary_min', models.IntegerField(verbose_name='Минимальня зарплата')),
                ('salary_max', models.IntegerField(verbose_name='Максимальная зарплата')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Опубликовано')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='job_site_app.company', verbose_name='Компания')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialty', to='job_site_app.specialty', verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_username', models.CharField(default='DEFAULT VALUE', max_length=50, verbose_name='Имя')),
                ('written_phone', models.CharField(default='DEFAULT VALUE', max_length=50, verbose_name='Телефон')),
                ('written_cover_letter', models.TextField(default='DEFAULT VALUE', verbose_name='Сопроводительное письмо')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='job_site_app.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
                'ordering': ['written_username'],
            },
        ),
    ]
