# Generated by Django 4.0.4 on 2022-05-03 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_site_app', '0002_alter_company_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='written_cover_letter',
            field=models.TextField(verbose_name='Сопроводительное письмо'),
        ),
        migrations.AlterField(
            model_name='application',
            name='written_phone',
            field=models.CharField(max_length=50, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='application',
            name='written_username',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('status', models.CharField(choices=[('not_looking', 'Не ищу работу'), ('considering', 'Рассматриваю предложения'), ('looking', 'Ищу работу')], max_length=50)),
                ('salary', models.IntegerField(verbose_name='Вознаграждение')),
                ('grade', models.CharField(choices=[('intern', 'Стажер'), ('junior', 'Джуниор'), ('middle', 'Миддл'), ('senior', 'Синьор'), ('lead', 'Лид')], max_length=50)),
                ('education', models.TextField(verbose_name='Образование')),
                ('experience', models.TextField(verbose_name='Опыт работы')),
                ('portfolio', models.URLField()),
                ('owner', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='job_site_app.specialty', verbose_name='Специализация')),
            ],
        ),
    ]
